export const allPets = [
  { id: 1, name: 'Whiskers', img: '/src/assets/photos/1.jpg' },
  { id: 2, name: 'Nibbles', img: '/src/assets/photos/2.jpg' },
  { id: 3, name: 'Squeaky', img: '/src/assets/photos/3.jpg' },
  //   { id: 4, name: 'Fuzzy', img: '' },
  //   { id: 5, name: 'Pip', img: '' },
  //   { id: 6, name: 'Cheddar', img: '' },
  //   { id: 7, name: 'Bubbles', img: '' },
  //   { id: 8, name: 'Marble', img: '' },
  //   { id: 9, name: 'Peanut', img: '' },
  //   { id: 10, name: 'Snickers', img: '' },
  //   { id: 11, name: 'Buttons', img: '' },
  //   { id: 12, name: 'Patch', img: '' },
  //   { id: 13, name: 'Hazel', img: '' },
  //   { id: 14, name: 'Gizmo', img: '' },
  //   { id: 15, name: 'Chipper', img: '' },
  //   { id: 16, name: 'Cinnamon', img: '' },
  //   { id: 17, name: 'Nutmeg', img: '' },
  //   { id: 18, name: 'Oreo', img: '' },
  //   { id: 19, name: 'Muffin', img: '' },
  //   { id: 20, name: 'Pumpkin', img: '' },
  //   { id: 21, name: 'Tinker', img: '' },
  //   { id: 22, name: 'Sprout', img: '' },
  //   { id: 23, name: 'Chester', img: '' },
  //   { id: 24, name: 'Daisy', img: '' },
  //   { id: 25, name: 'Mittens', img: '' },
  //   { id: 26, name: 'Rascal', img: '' },
  //   { id: 27, name: 'Pixie', img: '' },
  //   { id: 28, name: 'Scooter', img: '' },
  //   { id: 29, name: 'Patches', img: '' },
  //   { id: 30, name: 'Nugget', img: '' },
  //   { id: 31, name: 'Waffles', img: '' },
  //   { id: 32, name: 'Pebbles', img: '' },
  //   { id: 33, name: 'Biscuit', img: '' },
  //   { id: 34, name: 'Snickerdoodle', img: '' },
  //   { id: 35, name: 'Fudge', img: '' },
  //   { id: 36, name: 'Truffles', img: '' },
  //   { id: 37, name: 'Cupcake', img: '' },
  //   { id: 38, name: 'Twinkle', img: '' },
  //   { id: 39, name: 'Blossom', img: '' },
  //   { id: 40, name: 'Willow', img: '' },
  //   { id: 41, name: 'Mochi', img: '' },
  //   { id: 42, name: 'Toffee', img: '' },
  //   { id: 43, name: 'Coco', img: '' },
  //   { id: 44, name: 'Peaches', img: '' },
  //   { id: 45, name: 'Doodle', img: '' },
  //   { id: 46, name: 'Mocha', img: '' },
  //   { id: 47, name: 'Skittles', img: '' },
  //   { id: 48, name: 'Butterscotch', img: '' },
];
